spring:
  datasource:
    druid:
      master:
        url: jdbc:mysql://localhost:3306/bang-ry?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
  redis:
    host: localhost

minio:
  endpoint: http://localhost:9000


